config/routes.rb
Rails.application.routes.draw do

  get 'bulk_insert_texts/index'

  resources :push_texts
  resources :registrants
  devise_for :user, only: :none
  devise_scope :user do
    get :sign_in, controller: 'users/sessions', action: :new
  end
  resource :user, only: :none do
    ## ログインページ
    devise_scope :user do
      resource :session, only: [:create, :destroy], module: :users
    end
  end

  resource :bulk_insert_texts, only: [:index] do
    post :bulk_create
  end

  ## トップページ
  root to: 'registrants#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/push_text.rb
class PushText < ApplicationRecord
  belongs_to :registrant
end

app/controllers/push_texts_controller.rb
class PushTextsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_push_text, only: [:show, :edit, :update, :destroy]
  before_action :set_search_params, only: [:index]
  before_action :set_selectable_registrant, only: [:index, :new, :create, :edit, :update]

  # GET /push_texts
  # GET /push_texts.json
  def index
    @q = PushText.search(params[:q])
    @push_texts = @q.result.includes(:registrant).references(:registrant).order(:code, :pushed_at)
  end

  # GET /push_texts/1
  # GET /push_texts/1.json
  def show
  end

  # GET /push_texts/new
  def new
    @push_text = PushText.new
  end

  # GET /push_texts/1/edit
  def edit
  end

  # POST /push_texts
  # POST /push_texts.json
  def create
    @push_text = PushText.new(push_text_params)

    respond_to do |format|
      if @push_text.save
        format.html { redirect_to @push_text, notice: t("views.common.success_create", record: record) }
        format.json { render :show, status: :created, location: @push_text }
      else
        format.html { render :new }
        format.json { render json: @push_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /push_texts/1
  # PATCH/PUT /push_texts/1.json
  def update
    respond_to do |format|
      if @push_text.update(push_text_params)
        format.html { redirect_to @push_text, notice: t("views.common.success_update", record: record) }
        format.json { render :show, status: :ok, location: @push_text }
      else
        format.html { render :edit }
        format.json { render json: @push_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /push_texts/1
  # DELETE /push_texts/1.json
  def destroy
    @push_text.destroy
    respond_to do |format|
      format.html { redirect_to push_texts_url, notice: t("views.common.success_delete", record: record) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_push_text
    @push_text = PushText.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def push_text_params
    params.require(:push_text).permit(:registrant_id, :detail, :pushed_at)
  end

  def search_params
    params.require(:q).permit(:code_eq, :registrant_id_eq)
  end

  def set_search_params
    if !params[:q].present? && params[:reg_id].present?
      params[:q] = {}
      params[:q][:registrant_id_eq] = params[:reg_id].to_i
    elsif !params[:q].present? && params[:code].present?
      params[:q] = {}
      params[:q][:code_eq] = params[:code]
    end
  end

  def set_selectable_registrant
    @selectable_registrant = Registrant.all
  end

  def record
    t("activerecord.models.push_text")
  end
end

app/helpers/push_texts_helper.rb
module PushTextsHelper
end

app/views/push_texts/_form.html.haml
= form_for @push_text do |f|
  - if @push_text.errors.any?
    #error_explanation
      %h2= "#{pluralize(@push_text.errors.count, "error")} prohibited this push_text from being saved:"
      %ul
        - @push_text.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-12
      .box
        .box-body

          .form-group
            = f.label :code, class: "put-form-label"
            = f.text_field :code, class: "form-control"
          .form-group
            = f.label :registrant, class: "put-form-label"
            = f.collection_select :registrant_id, @selectable_registrant, :id, :code, {prompt: ""}, {class: "form-control put-form-select"}
          .form-group
            = f.label :detail, class: "put-form-label"
            = f.text_area :detail, class: "form-control"
          .form-group
            = f.label :pushed_at, class: "put-form-label"
            %br
            = f.datetime_select :pushed_at, {include_blank: false}, {class: "form-control put-form-datetime"}
          = f.submit t("views.common.save_btn")

app/views/push_texts/edit.html.haml
%section.content-header
  %h3= t("views.push_text.edit_tit")

%section.content.container-fluid
  = render 'form'

  = link_to t("views.common.show_btn"), @push_text, class: 'btn btn-default'
  \|
  = link_to t("views.common.back_btn"), push_texts_path, class: 'btn btn-default'

app/views/push_texts/index.html.haml
%section.content-header
  %h2= t("views.push_text.index_tit")

%section.content.container-fluid
  .put-search-form.box.box-default
    .box-body
      = search_form_for(@q, url: push_texts_path) do |f|
        = f.label :code_ep, t("activerecord.attributes.push_text.code")
        = f.search_field :code_eq

        = f.label :registrant_id_ep, t("activerecord.attributes.push_text.registrant")
        = f.collection_select :registrant_id_eq, @selectable_registrant, :id, :code, include_blank: true
        = f.submit

  .row
    .col-md-12
      .box
        .box-body
          %table.table.table-striped
            %tbody
              %tr
                %th= t("activerecord.attributes.push_text.code")
                %th= t("activerecord.attributes.push_text.registrant")
                %th= t("activerecord.attributes.push_text.detail")
                %th= t("activerecord.attributes.push_text.pushed_at")
                %th
                %th
                %th

              - @push_texts.each do |push_text|
                %tr
                  %td= push_text.code
                  %td= push_text.registrant.code
                  %td= push_text.detail
                  %td= push_text.pushed_at
                  %td= link_to t("views.common.show_btn"), push_text, class: 'btn btn-xs btn-default'
                  %td= link_to t("views.common.edit_btn"), edit_push_text_path(push_text), class: 'btn btn-xs btn-default'
                  %td= link_to t("views.common.delete_btn"), push_text, method: :delete, data: { confirm: t("activerecord.confirms.messages.delete") }, class: 'btn btn-xs btn-default'

  = link_to t("views.common.new_btn"), bulk_insert_texts_index_path, class: 'btn btn-default'
  \|
  = link_to t("views.common.back_btn"), registrants_path, class: 'btn btn-default'

app/views/push_texts/new.html.haml
%section.content-header
  %h3= t("views.push_text.new_tit")

%section.content.container-fluid
  = render 'form'

  = link_to t("views.common.back_btn"), push_texts_path

app/views/push_texts/show.html.haml
%section.content-header
  %h3= t("views.push_text.show_tit")

%section.content.container-fluid
  %p#notice= notice

  .row
    .col-md-8
      .box.box-default
        .box-body
          %p
            %b= t("activerecord.attributes.push_text.code") + ":"
            = @push_text.code
          %p
            %b= t("activerecord.attributes.push_text.registrant") + ":"
            = @push_text.registrant.code
          %p
            %b= t("activerecord.attributes.push_text.detail") + ":"
            = @push_text.detail
          %p
            %b= t("activerecord.attributes.push_text.pushed_at") + ":"
            = @push_text.pushed_at

  = link_to t("views.common.edit_btn"), edit_push_text_path(@push_text), class: 'btn btn-default'
  \|
  = link_to t("views.common.back_btn"), push_texts_path, class: 'btn btn-default'