config/routes.rb
Rails.application.routes.draw do

  get 'bulk_insert_texts/index'

  resources :push_texts
  resources :registrants
  devise_for :user, only: :none
  devise_scope :user do
    get :sign_in, controller: 'users/sessions', action: :new
  end
  resource :user, only: :none do
    ## ログインページ
    devise_scope :user do
      resource :session, only: [:create, :destroy], module: :users
    end
  end

  resource :bulk_insert_texts, only: [:index] do
    post :bulk_create
  end

  ## トップページ
  root to: 'registrants#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/registrant.rb
class Registrant < ApplicationRecord
  has_many :push_texts
end

app/controllers/registrants_controller.rb
class RegistrantsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_registrant, only: [:show, :edit, :update, :destroy]
  before_action :set_device_type_hash, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  protect_from_forgery except: :destroy

  # GET /registrants
  # GET /registrants.json
  def index
    @registrants = Registrant.all.order(:code)
  end

  # GET /registrants/1
  # GET /registrants/1.json
  def show
  end

  # GET /registrants/new
  def new
    @registrant = Registrant.new
  end

  # GET /registrants/1/edit
  def edit
  end

  # POST /registrants
  # POST /registrants.json
  def create
    @registrant = Registrant.new(registrant_params)

    respond_to do |format|
      if @registrant.save
        format.html { redirect_to @registrant, notice: t("views.common.success_create", record: record) }
        format.json { render :show, status: :created, location: @registrant }
      else
        format.html { render :new }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registrants/1
  # PATCH/PUT /registrants/1.json
  def update
    respond_to do |format|
      if @registrant.update(registrant_params)
        format.html { redirect_to @registrant, notice: t("views.common.success_update", record: record) }
        format.json { render :show, status: :ok, location: @registrant }
      else
        format.html { render :edit }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrants/1
  # DELETE /registrants/1.json
  def destroy
    @registrant.destroy
    respond_to do |format|
      format.html { redirect_to registrants_url, notice: t("views.common.success_delete", record: record) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_registrant
    @registrant = Registrant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def registrant_params
    params.require(:registrant).permit(:name, :device_info, :device_type)
  end

  def set_device_type_hash
    @device_type_hash = Code.get_val_with_name_by_code('DEVICE_TYPE')
  end

  def record
    t("activerecord.models.registrant")
  end
end

app/helpers/registrants_helper.rb
module RegistrantsHelper
end

app/views/registrants/_form.html.haml
= form_for @registrant do |f|
  - if @registrant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@registrant.errors.count, "error")} prohibited this registrant from being saved:"
      %ul
        - @registrant.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-12
      .box
        .box-body

          .form-group
            = f.label :code, class: "res-form-label"
            = f.text_field :code, class: "form-control"
          .form-group
            = f.label :name, class: "res-form-label"
            = f.text_field :name, class: "form-control"
          .form-group
            = f.label :device_info, class: "res-form-label"
            = f.text_field :device_info, class: "form-control"
          .form-group
            = f.label :device_type, class: "res-form-label"
            .radio
              %label
                = f.radio_button :device_type, "1"
                = @device_type_hash["1"]
            .radio
              %label
                = f.radio_button :device_type, "2"
                = @device_type_hash["2"]
          = f.submit t("views.common.save_btn")

app/views/registrants/edit.html.haml
%section.content-header
  %h3= t("views.registrant.edit_tit")

%section.content.container-fluid
  = render 'form'

  = link_to t("views.common.show_btn"), @registrant, class: 'btn btn-default'
  \|
  = link_to t("views.common.back_btn"), registrants_path, class: 'btn btn-default'

app/views/registrants/index.html.haml
%section.content-header
  %h2= t("views.registrant.index_tit")

%section.content.container-fluid
  .row
    .col-md-12
      .box
        .box-body
          %table.table.table-striped
            %tbody
              %tr
                %th= t("activerecord.attributes.registrant.code")
                %th= t("activerecord.attributes.registrant.name")
                %th= t("activerecord.attributes.registrant.device_info")
                %th= t("activerecord.attributes.registrant.device_type")
                %th
                %th
                %th
                %th
              - @registrants.each do |registrant|
                %tr
                  %td= registrant.code
                  %td= registrant.name
                  %td= registrant.device_info
                  %td= @device_type_hash[registrant.device_type]
                  %td= link_to t("views.registrant.push_txt_btn"), push_texts_path(reg_id: registrant.id), class: 'btn btn-xs btn-default'
                  %td= link_to t("views.common.show_btn"), registrant, class: 'btn btn-xs btn-default'
                  %td= link_to t("views.common.edit_btn"), edit_registrant_path(registrant), class: 'btn btn-xs btn-default'
                  %td= link_to t("views.common.delete_btn"), registrant, method: :delete, data: { confirm: t("activerecord.confirms.messages.delete") }, class: 'btn btn-xs btn-default'

  = link_to t("views.common.new_btn"), new_registrant_path, class: 'btn btn-default'

app/views/registrants/new.html.haml
%section.content-header
  %h3= t("views.registrant.new_tit")

%section.content.container-fluid
  = render 'form'

  = link_to t("views.common.back_btn"), registrants_path, class: 'btn btn-default'

app/views/registrants/show.html.haml
%section.content-header
  %h3= t("views.registrant.show_tit")

%section.content.container-fluid
  %p#notice= notice

  .row
    .col-md-8
      .box.box-default
        .box-body
          %p
            %b= t("activerecord.attributes.registrant.code") + ":"
            %br
            = @registrant.code
          %p
            %b= t("activerecord.attributes.registrant.name") + ":"
            %br
            = @registrant.name
          %p
            %b= t("activerecord.attributes.registrant.device_info") + ":"
            %br
            = @registrant.device_info
          %p
            %b= t("activerecord.attributes.registrant.device_type") + ":"
            %br
            = @device_type_hash[@registrant.device_type]

  = link_to t("views.common.edit_btn"), edit_registrant_path(@registrant), class: 'btn btn-default'
  \|
  = link_to link_to t("views.common.back_btn"), registrants_path, class: 'btn btn-default'